langauge: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
- npm i travis webpack
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: qLppuLhS1YK5Ebd3+6PJ3REJ6vUOaYh1cQahGeGFPDjthouabIne1QGZciZ8KVn/6Wx6T6mBs1zN2fp5PcJ3hMGdLPXWoWJzwojb0BHY8ZKbGQePNXNZbOxLbBxJottbPwsWM4Cdz0L6SpNrBRzNoToxe9xTYx3DNsQVoyOSbnE5zCwfo5n4ckrgQyDmh7VeKKdjIypiKfIFeqQ0cJaGUZfikXZJRMmTMbVSJI/xMzGzBZlns7aezb7i9urEFwQkQMChKJeRS7UqB2trBMxLCZJn81t5GHLwOIG5gGkNF7n2osTNKG2gU7sUS/dtgSuC838tGl1MOw/jhs0cTWglZEJubutBGM6ovfzz8IS7otXgLBXt7CH2SelSr3kcUY4EjGw0JY/ys6m9kwf3lrBwjSJXKJ7Rg/nKc/IchUOjWooe4HHPVPQJb8hbhfD4U+ELWxf+BrmQln8blLOYaXsCmlzHwphsCXL2g0klnZVIHPBcEPz2JCDpbChNMwl068HbHY4eAYYHdJ2w4gamh2wbHxbOwxvrp0DpDuG2fjfssa+Qly5fvU6JjUwHjNoCzoTWd4w/lgr6ejxjVdjyFQFaMTW1yd+hryInW+/pCK7XDEE3zcyteiXtbrOKKPQjbmRNa9aqDh4CiFPlqab+UTb75nwlCpjRKF2oS9c6yQpyPI4=
  app: impactyouth
  on:
    repo: CharleeJennings/IMPACT
