langauge: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
- npm i travis webpack
script:
- npm test
- npm start
deploy:
  provider: heroku
  api_key:
    secure: cFi4r5b3arQT8fVpXRzJFlKvDKTwMGDxuiAZNcL7gNFJCyDIUWtYRUDRSDjFrvBdSr65+d6ujTpBI5+LHN4Fs4tO0Sl9EXIQnHJJ55gtFCX4mb8cvpBgshhpGZJLDUCDVYE1rbY3jDXHqjLEYZKPKw5ghNDpBcS7PGSFxLQ/uXNGBmnxDSeimTyNVsRvK19C9ogAJAo0h8bkjN2OA62MHgOFdDMFVe/b2J7yV/yCV/HjPQHhQD1X1eMbPKwD8rDBewqops+rshmWFAsLvl8qEnJQEluKXw/Y3UE2Y778Kg6KIr5oWd7BBZuzWu+u9nTfwd+au/IyXT+oedsYGctzLMz+nV4cQCQ5x/7nZmCB//Q2fOkZINmtrAP1Fc+HRUbP1Wz9b0X/a95FX+Fzm/m9RCMWIqUxaftl8fi9MCoA2tBYHFSbS8PgssHuvOh/PXM+UEUZSyYdy3qhOqjD10/mTp4JMLhOApoFn8vsCGVt8gigOtadfSOIxYUX+ON+Q86CAuth9lm6wkQPDEzluvngfXNl9EUQyIVXOx80GBwsxhDaCfM8YhSGzoKGzoKGLr/ilLRIic3Yypdy48gW7ZmPl8JeWYCAnbx24sshXciWm9RVYSOppIeYgzlE/CB27NQ+Jnr8s2DKuaIpUR8viojtSbNs+5yEvuRf523f2nWv+f0=
  app: impactyouth
  on:
    repo: CharleeJennings/IMPACT
