langauge: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
-npm i travis
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: XmIcZ+ya+iJSIWm0eWINivsS8TETvi1K6HAyFKtyL2w0r46NV4nPbwEz0rVJqPpS/bQ17Sj1Tvr98DKf1p62OSHtPPKMX+IUcNfLlHXvc2iCVtECLhZGEkmbTozN9h7Ah0GPSWz/Y2zQm3dSZ4L0TveFNzHaCYT6mrf2Xa3akp0mJ3l6yrjtfxgxlZUFx10c+FISn6u8U/fjZOxSIve3J6uk4IksvjFb+b0FqLn9r4on8o9klEKemErbZQSK61fG7CrrfglVn1lgiTyA3037OVMDlfjftb5pDj51GZbA+ruvW1pMsWS4yyI6HekTCvCBhkCDC4P/MRPaXwWHfVfX0iJ9wFtYNFL5gqNhmXMq6agqIHLxPPgPkhr5Pm6S+fqZ9H0LXXIzEQ6TV1W5mbu/zxoK+rMsDk+mHXUuT4euQTpoAEOddYGzFyivPHAIvjQGVdJgNVltn2umg9COLclz/txLd4eKnmolIpiITUjcpzOHs1qxAZpm+DJuuS3UFSdqeZT9//Sbgu9hBoUV+bb567eltJ8CH/BrObuBQ55z5Y6fcDNxOlWvixxtSCQRXreMQL+hs1wzvyVOxsIRiXTmxKmTEnBtm6RNqBGRcDSA7GTCjpJcowTntBdDqmQYCupjRVjPdkunf0+TWVzx1FZYUopMCobuS52gZKQtkeUUwOk=
  app: nishaskcreations
  on:
    repo: CharleeJennings/NishasCreations
