langauge: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
- npm i travis webpack now
script:
- npm test
- npm run 
deploy:
  provider: script
  script: npm run deploy
