langauge: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_install:
  - npm i
script:
  - echo "Deploying"
  - npm i -g firebase  -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
