langauge: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_install:
  - npm i
script:
  - npm test
  - npm i -g firebase  -g firebase-tools
deploy:
  provider: firebase
  token:
    secure: gq4U9pVqa6yF6I/07mUCqSFPC+to7dpA6Wa/L5OyEooxH0vnA0fHKllS1kxr8MrHDTsrybqF0RkB/LEmg2JCf4sP+fWV8kpjeFUXNgiFiX5a755uvl3ECYlH2PB+sgdH66tyUgu0BWHbHE22tzQntycyn9N1Jra4Qd7NTgbAS+pN4DZnGm9FKALuiwZOO8dolQ4UhH546eJQ3IOq9dmP4c8MMqWNPZ3lQrup++W5CREPvCZme1Qm6+22Klxn4JhTS7j+aLCVG+RwaEByV7OWHNA7TfEEMAyUOUul5EnsiIlNau0yrcyXOlsrFUoMTU5vbVgJ5h2Q2qh7VA5VmzrJMCKo/QkEdSDvpKBPgUzAEEf6pWyyufVDhNo8NpwYSGiwOm/1YMvnXrniFRo5ZgclBxLUZXCrCvCGQryZYx6Nc+KTUE4tbDOGUUFNc0dJedAkEabg8PTEpd5vrasXtW1rMJkcjE34dQSlVkasyqtfVBG9F23abmMfeh7uGyNFMI0J2g9m1F1gVC658LRHfiDxhQUj1xsml1aR0ScGsMzl/K88zCOx0swa6oIcpLijmt/q0aZU8OyiKvi15zqjLjsBXhz5ZjcusLxOZUAEMIn5Sn9EQBhCH+SlxYNyrGcb5/ONiTi/awf/pdmjdpJRDNzqv5043zk52Va6yUNPKFrgTzk=
env:
  global:
    secure: gq4U9pVqa6yF6I/07mUCqSFPC+to7dpA6Wa/L5OyEooxH0vnA0fHKllS1kxr8MrHDTsrybqF0RkB/LEmg2JCf4sP+fWV8kpjeFUXNgiFiX5a755uvl3ECYlH2PB+sgdH66tyUgu0BWHbHE22tzQntycyn9N1Jra4Qd7NTgbAS+pN4DZnGm9FKALuiwZOO8dolQ4UhH546eJQ3IOq9dmP4c8MMqWNPZ3lQrup++W5CREPvCZme1Qm6+22Klxn4JhTS7j+aLCVG+RwaEByV7OWHNA7TfEEMAyUOUul5EnsiIlNau0yrcyXOlsrFUoMTU5vbVgJ5h2Q2qh7VA5VmzrJMCKo/QkEdSDvpKBPgUzAEEf6pWyyufVDhNo8NpwYSGiwOm/1YMvnXrniFRo5ZgclBxLUZXCrCvCGQryZYx6Nc+KTUE4tbDOGUUFNc0dJedAkEabg8PTEpd5vrasXtW1rMJkcjE34dQSlVkasyqtfVBG9F23abmMfeh7uGyNFMI0J2g9m1F1gVC658LRHfiDxhQUj1xsml1aR0ScGsMzl/K88zCOx0swa6oIcpLijmt/q0aZU8OyiKvi15zqjLjsBXhz5ZjcusLxOZUAEMIn5Sn9EQBhCH+SlxYNyrGcb5/ONiTi/awf/pdmjdpJRDNzqv5043zk52Va6yUNPKFrgTzk=
